//+------------------------------------------------------------------+
//| smc_structure_EURUSD_D1_aa4974.mq5
//| Generated by QuantLab — 2026-07-04T02:25:43.290950+00:00
//| Pattern: smc_structure | TF: D1 | Symbol: EURUSD
//+------------------------------------------------------------------+
#property copyright "QuantLab"
#property version   "1"
#property strict

#include <Trade\Trade.mqh>

input double InpLotSize = 0.2;
input int    InpStopLoss = 60;
input int    InpTakeProfit = 248;
input int    InpTrailingStop = 70;
input int    InpMaxPositions = 1;

CTrade trade;
datetime lastBarTime = 0;

int OnInit() {
    trade.SetExpertMagicNumber(MAGIC_NUMBER);
    return(INIT_SUCCEEDED);
}

void OnTick() {
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    if(currentBarTime == lastBarTime) return;
    lastBarTime = currentBarTime;

    ManageTrailingStop();
    ExecuteStrategy();
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            count++;
    }
    return count;
}

void ManageTrailingStop() {
    if(InpTrailingStop <= 0) return;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) != _Symbol) continue;
        if(PositionGetInteger(POSITION_MAGIC) != MAGIC_NUMBER) continue;
        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSL = PositionGetDouble(POSITION_SL);
        ulong ticket = PositionGetInteger(POSITION_TICKET);
        if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - InpTrailingStop * _Point;
            if(newSL > currentSL + _Point)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        } else {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + InpTrailingStop * _Point;
            if(newSL < currentSL - _Point || currentSL == 0)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        }
    }
}

void CloseAll() {
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            trade.PositionClose(PositionGetInteger(POSITION_TICKET));
    }
}

#define MAGIC_NUMBER 102635

int emaFastHandle, rsiHandle, adxHandle, atrHandle;

int OnInit() {
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, 16, 0, MODE_EMA, PRICE_CLOSE);
    emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, 26, 0, MODE_EMA, PRICE_CLOSE);
    rsiHandle = iRSI(_Symbol, PERIOD_CURRENT, 13, PRICE_CLOSE);
    adxHandle = iADX(_Symbol, PERIOD_CURRENT, 14);
    atrHandle = iATR(_Symbol, PERIOD_CURRENT, 12);
    return INIT_SUCCEEDED;
}

void ExecuteStrategy() {
    if(CountPositions() >= InpMaxPositions) return;
    double emaFast[], rsi[], adxVal[], atrVal[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(rsi, true);
    ArraySetAsSeries(adxVal, true);
    ArraySetAsSeries(atrVal, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(rsiHandle, 0, 0, 3, rsi);
    CopyBuffer(adxHandle, 1, 0, 3, adxVal);
    CopyBuffer(atrHandle, 0, 0, 3, atrVal);

    double high1 = iHigh(_Symbol, PERIOD_CURRENT, 1);
    double low1 = iLow(_Symbol, PERIOD_CURRENT, 1);
    double high2 = iHigh(_Symbol, PERIOD_CURRENT, 2);
    double low2 = iLow(_Symbol, PERIOD_CURRENT, 2);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    bool bosBull = (high1 > high2 && emaFast[1] > emaFast[2]);
    bool bosBear = (low1 < low2 && emaFast[1] < emaFast[2]);

    if(bosBull && adxVal[1] > 27 && rsi[1] > 50) {
        double sl = ask - atrVal[1] * 0.9;
        double tp = ask + atrVal[1] * 0.9 * 2.5;
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "smc_structure_EURUSD_D1_aa4974_BUY");
    }
    if(bosBear && adxVal[1] > 27 && rsi[1] < 50) {
        double sl = bid + atrVal[1] * 0.9;
        double tp = bid - atrVal[1] * 0.9 * 2.5;
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "smc_structure_EURUSD_D1_aa4974_SELL");
    }
}
