//+------------------------------------------------------------------+
//| session_based_USDJPY_M5_cf9740.mq5
//| Generated by QuantLab — 2026-07-04T02:06:22.778585+00:00
//| Pattern: session_based | TF: M5 | Symbol: USDJPY
//+------------------------------------------------------------------+
#property copyright "QuantLab"
#property version   "1"
#property strict

#include <Trade\Trade.mqh>

input double InpLotSize = 0.01;
input int    InpStopLoss = 143;
input int    InpTakeProfit = 179;
input int    InpTrailingStop = 37;
input int    InpMaxPositions = 1;

CTrade trade;
datetime lastBarTime = 0;

int OnInit() {
    trade.SetExpertMagicNumber(MAGIC_NUMBER);
    return(INIT_SUCCEEDED);
}

void OnTick() {
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    if(currentBarTime == lastBarTime) return;
    lastBarTime = currentBarTime;

    ManageTrailingStop();
    ExecuteStrategy();
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            count++;
    }
    return count;
}

void ManageTrailingStop() {
    if(InpTrailingStop <= 0) return;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) != _Symbol) continue;
        if(PositionGetInteger(POSITION_MAGIC) != MAGIC_NUMBER) continue;
        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSL = PositionGetDouble(POSITION_SL);
        ulong ticket = PositionGetInteger(POSITION_TICKET);
        if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - InpTrailingStop * _Point;
            if(newSL > currentSL + _Point)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        } else {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + InpTrailingStop * _Point;
            if(newSL < currentSL - _Point || currentSL == 0)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        }
    }
}

void CloseAll() {
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            trade.PositionClose(PositionGetInteger(POSITION_TICKET));
    }
}

#define MAGIC_NUMBER 358601

int emaFastHandle, rsiHandle, adxHandle;

int OnInit() {
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, 7, 0, MODE_EMA, PRICE_CLOSE);
    rsiHandle = iRSI(_Symbol, PERIOD_CURRENT, 30, PRICE_CLOSE);
    adxHandle = iADX(_Symbol, PERIOD_CURRENT, 14);
    return INIT_SUCCEEDED;
}

void ExecuteStrategy() {
    if(CountPositions() >= InpMaxPositions) return;
    MqlDateTime dt;
    TimeCurrent(dt);
    int hour = dt.hour;
    if(hour < 6 || hour > 22) return;

    double emaFast[], rsi[], adxVal[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(rsi, true);
    ArraySetAsSeries(adxVal, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(rsiHandle, 0, 0, 3, rsi);
    CopyBuffer(adxHandle, 1, 0, 3, adxVal);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(adxVal[1] > 23) {
        if(rsi[1] < 32 && ask > emaFast[1]) {
            trade.Buy(InpLotSize, _Symbol, ask, ask - InpStopLoss * _Point, ask + InpTakeProfit * _Point, "session_based_USDJPY_M5_cf9740_BUY");
        }
        if(rsi[1] > 75 && bid < emaFast[1]) {
            trade.Sell(InpLotSize, _Symbol, bid, bid + InpStopLoss * _Point, bid - InpTakeProfit * _Point, "session_based_USDJPY_M5_cf9740_SELL");
        }
    }
}
