//+------------------------------------------------------------------+
//| killzone_trading_GBPUSD_D1_40341f.mq5
//| Generated by QuantLab — 2026-07-04T02:13:24.848717+00:00
//| Pattern: killzone_trading | TF: D1 | Symbol: GBPUSD
//+------------------------------------------------------------------+
#property copyright "QuantLab"
#property version   "1"
#property strict

#include <Trade\Trade.mqh>

input double InpLotSize = 0.2;
input int    InpStopLoss = 48;
input int    InpTakeProfit = 84;
input int    InpTrailingStop = 64;
input int    InpMaxPositions = 1;

CTrade trade;
datetime lastBarTime = 0;

int OnInit() {
    trade.SetExpertMagicNumber(MAGIC_NUMBER);
    return(INIT_SUCCEEDED);
}

void OnTick() {
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    if(currentBarTime == lastBarTime) return;
    lastBarTime = currentBarTime;

    ManageTrailingStop();
    ExecuteStrategy();
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            count++;
    }
    return count;
}

void ManageTrailingStop() {
    if(InpTrailingStop <= 0) return;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) != _Symbol) continue;
        if(PositionGetInteger(POSITION_MAGIC) != MAGIC_NUMBER) continue;
        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSL = PositionGetDouble(POSITION_SL);
        ulong ticket = PositionGetInteger(POSITION_TICKET);
        if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - InpTrailingStop * _Point;
            if(newSL > currentSL + _Point)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        } else {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + InpTrailingStop * _Point;
            if(newSL < currentSL - _Point || currentSL == 0)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        }
    }
}

void CloseAll() {
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            trade.PositionClose(PositionGetInteger(POSITION_TICKET));
    }
}

#define MAGIC_NUMBER 434686

int emaFastHandle, emaSlowHandle, volumeHandle;

int OnInit() {
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, 30, 0, MODE_EMA, PRICE_CLOSE);
    emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, 72, 0, MODE_EMA, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}

void ExecuteStrategy() {
    if(CountPositions() >= InpMaxPositions) return;
    MqlDateTime dt;
    TimeCurrent(dt);
    int hour = dt.hour;
    bool londonKillzone = (hour >= 7 && hour <= 10);
    bool nyKillzone = (hour >= 13 && hour <= 16);
    if(!londonKillzone && !nyKillzone) return;

    double emaFast[], emaSlow[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(emaSlow, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(emaSlowHandle, 0, 0, 3, emaSlow);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(emaFast[1] > emaSlow[1] && emaFast[2] < emaSlow[2]) {
        trade.Buy(InpLotSize, _Symbol, ask, ask - InpStopLoss * _Point, ask + InpTakeProfit * _Point, "killzone_trading_GBPUSD_D1_40341f_BUY");
    }
    if(emaFast[1] < emaSlow[1] && emaFast[2] > emaSlow[2]) {
        trade.Sell(InpLotSize, _Symbol, bid, bid + InpStopLoss * _Point, bid - InpTakeProfit * _Point, "killzone_trading_GBPUSD_D1_40341f_SELL");
    }
}
