"""Coding Agent — generates MQL5 Expert Advisors from strategy definitions."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from agents.base_agent import BaseAgent
from core.models import Strategy, StrategyPattern, Task
from core.logger import get_logger

log = get_logger("agent.coding")

_STRATEGIES_DIR = Path(__file__).resolve().parent.parent.parent / "strategies"
_STRATEGIES_DIR.mkdir(exist_ok=True)


class CodingAgent(BaseAgent):
    name = "coding"

    async def execute(self, task: Task) -> dict:
        strategy_data = task.params.get("strategy")
        if not strategy_data:
            return {"error": "No strategy data provided"}
        strategy = Strategy(**strategy_data)
        code = self._generate_mql5(strategy)
        version_dir = _STRATEGIES_DIR / strategy.name / f"v{strategy.version}"
        version_dir.mkdir(parents=True, exist_ok=True)
        ea_path = version_dir / f"{strategy.name}.mq5"
        ea_path.write_text(code, encoding="utf-8")
        log.info("Generated EA: %s", ea_path)
        return {"code_path": str(ea_path), "strategy_id": strategy.id}

    def _generate_mql5(self, s: Strategy) -> str:
        p = s.params
        if s.pattern == StrategyPattern.TREND_FOLLOWING:
            return self._trend_following_ea(s, p)
        elif s.pattern == StrategyPattern.MEAN_REVERSION:
            return self._mean_reversion_ea(s, p)
        elif s.pattern == StrategyPattern.SCALPING:
            return self._scalping_ea(s, p)
        elif s.pattern == StrategyPattern.BREAKOUT:
            return self._breakout_ea(s, p)
        elif s.pattern == StrategyPattern.SESSION_BASED:
            return self._session_ea(s, p)
        elif s.pattern == StrategyPattern.KILLZONE_TRADING:
            return self._killzone_ea(s, p)
        elif s.pattern == StrategyPattern.SMC_STRUCTURE:
            return self._smc_ea(s, p)
        else:
            return self._trend_following_ea(s, p)

    def _base_header(self, s: Strategy) -> str:
        return f"""//+------------------------------------------------------------------+
//| {s.name}.mq5
//| Generated by QuantLab — {datetime.now(timezone.utc).isoformat()}
//| Pattern: {s.pattern.value} | TF: {s.timeframe.value} | Symbol: {s.symbol}
//+------------------------------------------------------------------+
#property copyright "QuantLab"
#property version   "{s.version}"
#property strict

#include <Trade\\Trade.mqh>

input double InpLotSize = {s.params.lot_size};
input int    InpStopLoss = {s.params.stop_loss};
input int    InpTakeProfit = {s.params.take_profit};
input int    InpTrailingStop = {s.params.trailing_stop};
input int    InpMaxPositions = {s.params.max_positions};

CTrade trade;
datetime lastBarTime = 0;

int OnInit() {{
    trade.SetExpertMagicNumber(MAGIC_NUMBER);
    return(INIT_SUCCEEDED);
}}

void OnTick() {{
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    if(currentBarTime == lastBarTime) return;
    lastBarTime = currentBarTime;

    ManageTrailingStop();
    ExecuteStrategy();
}}

int CountPositions() {{
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {{
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            count++;
    }}
    return count;
}}

void ManageTrailingStop() {{
    if(InpTrailingStop <= 0) return;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {{
        if(PositionGetSymbol(i) != _Symbol) continue;
        if(PositionGetInteger(POSITION_MAGIC) != MAGIC_NUMBER) continue;
        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSL = PositionGetDouble(POSITION_SL);
        ulong ticket = PositionGetInteger(POSITION_TICKET);
        if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {{
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - InpTrailingStop * _Point;
            if(newSL > currentSL + _Point)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        }} else {{
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + InpTrailingStop * _Point;
            if(newSL < currentSL - _Point || currentSL == 0)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        }}
    }}
}}

void CloseAll() {{
    for(int i = PositionsTotal() - 1; i >= 0; i--) {{
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            trade.PositionClose(PositionGetInteger(POSITION_TICKET));
    }}
}}
"""

    def _trend_following_ea(self, s: Strategy, p) -> str:
        header = self._base_header(s)
        return header + f"""
#define MAGIC_NUMBER {abs(hash(s.name)) % 999999 + 100000}

int emaFastHandle, emaSlowHandle, adxHandle, atrHandle;

int OnInit() {{
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_fast}, 0, MODE_EMA, PRICE_CLOSE);
    emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_slow}, 0, MODE_EMA, PRICE_CLOSE);
    adxHandle = iADX(_Symbol, PERIOD_CURRENT, 14);
    atrHandle = iATR(_Symbol, PERIOD_CURRENT, {p.atr_period});
    return INIT_SUCCEEDED;
}}

void ExecuteStrategy() {{
    if(CountPositions() >= InpMaxPositions) return;

    double emaFast[], emaSlow[], adxVal[], atrVal[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(emaSlow, true);
    ArraySetAsSeries(adxVal, true);
    ArraySetAsSeries(atrVal, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(emaSlowHandle, 0, 0, 3, emaSlow);
    CopyBuffer(adxHandle, 1, 0, 3, adxVal);
    CopyBuffer(atrHandle, 0, 0, 3, atrVal);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(adxVal[1] < {p.adx_threshold}) return;

    if(emaFast[2] < emaSlow[2] && emaFast[1] > emaSlow[1] && adxVal[1] > {p.adx_threshold}) {{
        double sl = ask - InpStopLoss * _Point;
        double tp = ask + InpTakeProfit * _Point;
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "{s.name}_BUY");
    }}
    if(emaFast[2] > emaSlow[2] && emaFast[1] < emaSlow[1] && adxVal[1] > {p.adx_threshold}) {{
        double sl = bid + InpStopLoss * _Point;
        double tp = bid - InpTakeProfit * _Point;
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "{s.name}_SELL");
    }}
}}
"""

    def _mean_reversion_ea(self, s: Strategy, p) -> str:
        header = self._base_header(s)
        return header + f"""
#define MAGIC_NUMBER {abs(hash(s.name)) % 999999 + 100000}

int rsiHandle, bbHandle;

int OnInit() {{
    rsiHandle = iRSI(_Symbol, PERIOD_CURRENT, {p.rsi_period}, PRICE_CLOSE);
    bbHandle = iBands(_Symbol, PERIOD_CURRENT, {p.ema_fast}, 0, 2.0, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}}

void ExecuteStrategy() {{
    if(CountPositions() >= InpMaxPositions) return;
    double rsi[], bbUpper[], bbMiddle[], bbLower[];
    ArraySetAsSeries(rsi, true);
    ArraySetAsSeries(bbUpper, true);
    ArraySetAsSeries(bbMiddle, true);
    ArraySetAsSeries(bbLower, true);
    CopyBuffer(rsiHandle, 0, 0, 3, rsi);
    CopyBuffer(bbHandle, 1, 0, 3, bbUpper);
    CopyBuffer(bbHandle, 0, 0, 3, bbMiddle);
    CopyBuffer(bbHandle, 2, 0, 3, bbLower);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(rsi[1] < {p.rsi_oversold} && ask <= bbLower[1]) {{
        double sl = ask - InpStopLoss * _Point;
        double tp = bbMiddle[1];
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "{s.name}_BUY");
    }}
    if(rsi[1] > {p.rsi_overbought} && bid >= bbUpper[1]) {{
        double sl = bid + InpStopLoss * _Point;
        tp = bbMiddle[1];
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "{s.name}_SELL");
    }}
}}
"""

    def _scalping_ea(self, s: Strategy, p) -> str:
        header = self._base_header(s)
        return header + f"""
#define MAGIC_NUMBER {abs(hash(s.name)) % 999999 + 100000}

int emaFastHandle, emaSlowHandle;

int OnInit() {{
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_fast}, 0, MODE_EMA, PRICE_CLOSE);
    emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_slow}, 0, MODE_EMA, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}}

void ExecuteStrategy() {{
    if(CountPositions() >= InpMaxPositions) return;
    double emaFast[], emaSlow[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(emaSlow, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(emaSlowHandle, 0, 0, 3, emaSlow);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(emaFast[1] > emaSlow[1] && emaFast[0] > emaSlow[0]) {{
        double sl = ask - InpStopLoss * _Point;
        double tp = ask + InpTakeProfit * _Point;
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "{s.name}_BUY");
    }}
    if(emaFast[1] < emaSlow[1] && emaFast[0] < emaSlow[0]) {{
        double sl = bid + InpStopLoss * _Point;
        double tp = bid - InpTakeProfit * _Point;
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "{s.name}_SELL");
    }}
}}
"""

    def _breakout_ea(self, s: Strategy, p) -> str:
        header = self._base_header(s)
        return header + f"""
#define MAGIC_NUMBER {abs(hash(s.name)) % 999999 + 100000}

int atrHandle;

int OnInit() {{
    atrHandle = iATR(_Symbol, PERIOD_CURRENT, {p.atr_period});
    return INIT_SUCCEEDED;
}}

void ExecuteStrategy() {{
    if(CountPositions() >= InpMaxPositions) return;
    double atrVal[];
    ArraySetAsSeries(atrVal, true);
    CopyBuffer(atrHandle, 0, 0, 3, atrVal);

    double high1 = iHigh(_Symbol, PERIOD_CURRENT, 1);
    double low1 = iLow(_Symbol, PERIOD_CURRENT, 1);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(ask > high1) {{
        double sl = ask - atrVal[1] * {p.atr_multiplier};
        double tp = ask + atrVal[1] * {p.atr_multiplier} * 2;
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "{s.name}_BUY");
    }}
    if(bid < low1) {{
        double sl = bid + atrVal[1] * {p.atr_multiplier};
        double tp = bid - atrVal[1] * {p.atr_multiplier} * 2;
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "{s.name}_SELL");
    }}
}}
"""

    def _session_ea(self, s: Strategy, p) -> str:
        header = self._base_header(s)
        return header + f"""
#define MAGIC_NUMBER {abs(hash(s.name)) % 999999 + 100000}

int emaFastHandle, rsiHandle, adxHandle;

int OnInit() {{
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_fast}, 0, MODE_EMA, PRICE_CLOSE);
    rsiHandle = iRSI(_Symbol, PERIOD_CURRENT, {p.rsi_period}, PRICE_CLOSE);
    adxHandle = iADX(_Symbol, PERIOD_CURRENT, 14);
    return INIT_SUCCEEDED;
}}

void ExecuteStrategy() {{
    if(CountPositions() >= InpMaxPositions) return;
    MqlDateTime dt;
    TimeCurrent(dt);
    int hour = dt.hour;
    if(hour < {p.session_start} || hour > {p.session_end}) return;

    double emaFast[], rsi[], adxVal[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(rsi, true);
    ArraySetAsSeries(adxVal, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(rsiHandle, 0, 0, 3, rsi);
    CopyBuffer(adxHandle, 1, 0, 3, adxVal);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(adxVal[1] > {p.adx_threshold}) {{
        if(rsi[1] < {p.rsi_oversold} && ask > emaFast[1]) {{
            trade.Buy(InpLotSize, _Symbol, ask, ask - InpStopLoss * _Point, ask + InpTakeProfit * _Point, "{s.name}_BUY");
        }}
        if(rsi[1] > {p.rsi_overbought} && bid < emaFast[1]) {{
            trade.Sell(InpLotSize, _Symbol, bid, bid + InpStopLoss * _Point, bid - InpTakeProfit * _Point, "{s.name}_SELL");
        }}
    }}
}}
"""

    def _killzone_ea(self, s: Strategy, p) -> str:
        header = self._base_header(s)
        return header + f"""
#define MAGIC_NUMBER {abs(hash(s.name)) % 999999 + 100000}

int emaFastHandle, emaSlowHandle, volumeHandle;

int OnInit() {{
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_fast}, 0, MODE_EMA, PRICE_CLOSE);
    emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_slow}, 0, MODE_EMA, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}}

void ExecuteStrategy() {{
    if(CountPositions() >= InpMaxPositions) return;
    MqlDateTime dt;
    TimeCurrent(dt);
    int hour = dt.hour;
    bool londonKillzone = (hour >= 7 && hour <= 10);
    bool nyKillzone = (hour >= 13 && hour <= 16);
    if(!londonKillzone && !nyKillzone) return;

    double emaFast[], emaSlow[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(emaSlow, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(emaSlowHandle, 0, 0, 3, emaSlow);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(emaFast[1] > emaSlow[1] && emaFast[2] < emaSlow[2]) {{
        trade.Buy(InpLotSize, _Symbol, ask, ask - InpStopLoss * _Point, ask + InpTakeProfit * _Point, "{s.name}_BUY");
    }}
    if(emaFast[1] < emaSlow[1] && emaFast[2] > emaSlow[2]) {{
        trade.Sell(InpLotSize, _Symbol, bid, bid + InpStopLoss * _Point, bid - InpTakeProfit * _Point, "{s.name}_SELL");
    }}
}}
"""

    def _smc_ea(self, s: Strategy, p) -> str:
        header = self._base_header(s)
        return header + f"""
#define MAGIC_NUMBER {abs(hash(s.name)) % 999999 + 100000}

int emaFastHandle, rsiHandle, adxHandle, atrHandle;

int OnInit() {{
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_fast}, 0, MODE_EMA, PRICE_CLOSE);
    emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, {p.ema_slow}, 0, MODE_EMA, PRICE_CLOSE);
    rsiHandle = iRSI(_Symbol, PERIOD_CURRENT, {p.rsi_period}, PRICE_CLOSE);
    adxHandle = iADX(_Symbol, PERIOD_CURRENT, 14);
    atrHandle = iATR(_Symbol, PERIOD_CURRENT, {p.atr_period});
    return INIT_SUCCEEDED;
}}

void ExecuteStrategy() {{
    if(CountPositions() >= InpMaxPositions) return;
    double emaFast[], rsi[], adxVal[], atrVal[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(rsi, true);
    ArraySetAsSeries(adxVal, true);
    ArraySetAsSeries(atrVal, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(rsiHandle, 0, 0, 3, rsi);
    CopyBuffer(adxHandle, 1, 0, 3, adxVal);
    CopyBuffer(atrHandle, 0, 0, 3, atrVal);

    double high1 = iHigh(_Symbol, PERIOD_CURRENT, 1);
    double low1 = iLow(_Symbol, PERIOD_CURRENT, 1);
    double high2 = iHigh(_Symbol, PERIOD_CURRENT, 2);
    double low2 = iLow(_Symbol, PERIOD_CURRENT, 2);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    bool bosBull = (high1 > high2 && emaFast[1] > emaFast[2]);
    bool bosBear = (low1 < low2 && emaFast[1] < emaFast[2]);

    if(bosBull && adxVal[1] > {p.adx_threshold} && rsi[1] > 50) {{
        double sl = ask - atrVal[1] * {p.atr_multiplier};
        double tp = ask + atrVal[1] * {p.atr_multiplier} * 2.5;
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "{s.name}_BUY");
    }}
    if(bosBear && adxVal[1] > {p.adx_threshold} && rsi[1] < 50) {{
        double sl = bid + atrVal[1] * {p.atr_multiplier};
        double tp = bid - atrVal[1] * {p.atr_multiplier} * 2.5;
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "{s.name}_SELL");
    }}
}}
"""
