//+------------------------------------------------------------------+
//| mean_reversion_GBPUSD_D1_ae8e0d.mq5
//| Generated by QuantLab — 2026-07-04T01:53:52.617815+00:00
//| Pattern: mean_reversion | TF: D1 | Symbol: GBPUSD
//+------------------------------------------------------------------+
#property copyright "QuantLab"
#property version   "1"
#property strict

#include <Trade\Trade.mqh>

input double InpLotSize = 0.01;
input int    InpStopLoss = 76;
input int    InpTakeProfit = 80;
input int    InpTrailingStop = 51;
input int    InpMaxPositions = 1;

CTrade trade;
datetime lastBarTime = 0;

int OnInit() {
    trade.SetExpertMagicNumber(MAGIC_NUMBER);
    return(INIT_SUCCEEDED);
}

void OnTick() {
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    if(currentBarTime == lastBarTime) return;
    lastBarTime = currentBarTime;

    ManageTrailingStop();
    ExecuteStrategy();
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            count++;
    }
    return count;
}

void ManageTrailingStop() {
    if(InpTrailingStop <= 0) return;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) != _Symbol) continue;
        if(PositionGetInteger(POSITION_MAGIC) != MAGIC_NUMBER) continue;
        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSL = PositionGetDouble(POSITION_SL);
        ulong ticket = PositionGetInteger(POSITION_TICKET);
        if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - InpTrailingStop * _Point;
            if(newSL > currentSL + _Point)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        } else {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + InpTrailingStop * _Point;
            if(newSL < currentSL - _Point || currentSL == 0)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        }
    }
}

void CloseAll() {
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            trade.PositionClose(PositionGetInteger(POSITION_TICKET));
    }
}

#define MAGIC_NUMBER 838251

int rsiHandle, bbHandle;

int OnInit() {
    rsiHandle = iRSI(_Symbol, PERIOD_CURRENT, 20, PRICE_CLOSE);
    bbHandle = iBands(_Symbol, PERIOD_CURRENT, 8, 0, 2.0, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}

void ExecuteStrategy() {
    if(CountPositions() >= InpMaxPositions) return;
    double rsi[], bbUpper[], bbMiddle[], bbLower[];
    ArraySetAsSeries(rsi, true);
    ArraySetAsSeries(bbUpper, true);
    ArraySetAsSeries(bbMiddle, true);
    ArraySetAsSeries(bbLower, true);
    CopyBuffer(rsiHandle, 0, 0, 3, rsi);
    CopyBuffer(bbHandle, 1, 0, 3, bbUpper);
    CopyBuffer(bbHandle, 0, 0, 3, bbMiddle);
    CopyBuffer(bbHandle, 2, 0, 3, bbLower);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(rsi[1] < 27 && ask <= bbLower[1]) {
        double sl = ask - InpStopLoss * _Point;
        double tp = bbMiddle[1];
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "mean_reversion_GBPUSD_D1_ae8e0d_BUY");
    }
    if(rsi[1] > 81 && bid >= bbUpper[1]) {
        double sl = bid + InpStopLoss * _Point;
        tp = bbMiddle[1];
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "mean_reversion_GBPUSD_D1_ae8e0d_SELL");
    }
}
