//+------------------------------------------------------------------+
//| scalping_USDCAD_M5_dbbcd8.mq5
//| Generated by QuantLab — 2026-07-04T02:27:28.657462+00:00
//| Pattern: scalping | TF: M5 | Symbol: USDCAD
//+------------------------------------------------------------------+
#property copyright "QuantLab"
#property version   "1"
#property strict

#include <Trade\Trade.mqh>

input double InpLotSize = 0.05;
input int    InpStopLoss = 7;
input int    InpTakeProfit = 12;
input int    InpTrailingStop = 80;
input int    InpMaxPositions = 1;

CTrade trade;
datetime lastBarTime = 0;

int OnInit() {
    trade.SetExpertMagicNumber(MAGIC_NUMBER);
    return(INIT_SUCCEEDED);
}

void OnTick() {
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    if(currentBarTime == lastBarTime) return;
    lastBarTime = currentBarTime;

    ManageTrailingStop();
    ExecuteStrategy();
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            count++;
    }
    return count;
}

void ManageTrailingStop() {
    if(InpTrailingStop <= 0) return;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) != _Symbol) continue;
        if(PositionGetInteger(POSITION_MAGIC) != MAGIC_NUMBER) continue;
        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSL = PositionGetDouble(POSITION_SL);
        ulong ticket = PositionGetInteger(POSITION_TICKET);
        if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - InpTrailingStop * _Point;
            if(newSL > currentSL + _Point)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        } else {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + InpTrailingStop * _Point;
            if(newSL < currentSL - _Point || currentSL == 0)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        }
    }
}

void CloseAll() {
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            trade.PositionClose(PositionGetInteger(POSITION_TICKET));
    }
}

#define MAGIC_NUMBER 898423

int emaFastHandle, emaSlowHandle;

int OnInit() {
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, 11, 0, MODE_EMA, PRICE_CLOSE);
    emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, 91, 0, MODE_EMA, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}

void ExecuteStrategy() {
    if(CountPositions() >= InpMaxPositions) return;
    double emaFast[], emaSlow[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(emaSlow, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(emaSlowHandle, 0, 0, 3, emaSlow);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(emaFast[1] > emaSlow[1] && emaFast[0] > emaSlow[0]) {
        double sl = ask - InpStopLoss * _Point;
        double tp = ask + InpTakeProfit * _Point;
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "scalping_USDCAD_M5_dbbcd8_BUY");
    }
    if(emaFast[1] < emaSlow[1] && emaFast[0] < emaSlow[0]) {
        double sl = bid + InpStopLoss * _Point;
        double tp = bid - InpTakeProfit * _Point;
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "scalping_USDCAD_M5_dbbcd8_SELL");
    }
}
