//+------------------------------------------------------------------+
//| Quant_XAUUSD_Alpha_Ultimate v4.5                                  |
//| Generated by QuantLab — FTMO Challenge Optimized                 |
//| Magic Number: 202699                                             |
//+------------------------------------------------------------------+
#property copyright "QuantLab"
#property version   "4.5"
#property strict

#include <Trade\Trade.mqh>

//--- Input Parameters
// Risk Management
input double InpInitialBalance     = 100000.0;  // Initial Balance
input double InpRiskPerTradePct    = 0.7;        // Risk Per Trade %
input double InpMaxDailyLossPct    = 4.0;        // Max Daily Loss %
input double InpMaxTotalLossPct    = 10.0;       // Max Total Loss %
input double InpTargetProfitPct    = 10.0;       // Target Profit %
input bool   InpUnlimitedProfit    = true;       // Unlimited Profit
input int    InpMaxTradeDuration   = 120;        // Max Trade Duration (min)
input double InpRiskTaperDDmult    = 1.0;        // Risk Taper DD Multiplier

// Trade Management
input double InpTargetRatio        = 3.0;        // Target R:R Ratio
input double InpTrailingATRmult    = 1.5;        // Trailing ATR Multiplier
input double InpPartialProfitPct   = 0.50;       // Partial Profit % of TP
input double InpSLatrMultiplier    = 1.2;        // SL ATR Multiplier

// Entry Filters
input int    InpRegimePeriod       = 20;         // ATR Period (M15)
input double InpMinEfficiency      = 0.08;       // Min Efficiency Ratio
input int    InpMinVolumeRatio     = 15;         // Min Volume Ratio
input int    InpMaxSpreadPips      = 30;         // Max Spread Pips
input int    InpConsecutiveLossLimit = 3;        // Consecutive Loss Limit

// HTF Filters
input bool   InpEnableHTFFilter    = true;       // Enable HTF Filter
input int    InpEMAperiodH1        = 50;         // EMA Period H1
input int    InpMinMAalignment     = 10;         // Min MA Alignment Pips
input bool   InpEnableM5filter     = true;       // Enable M5 Filter
input int    InpM5trendBars        = 5;          // M5 Trend Bars

// Sessions (UTC)
input int    InpLondonStart        = 3;          // London Start Hour
input int    InpLondonEnd          = 12;         // London End Hour
input int    InpNYStart            = 13;         // NY Start Hour
input int    InpNYEnd              = 21;         // NY End Hour
input int    InpAsiaStart          = 0;          // Asia Start Hour
input int    InpAsiaEnd            = 3;          // Asia End Hour

// Protection
input bool   InpEnableFridayClose  = true;       // Friday Close
input int    InpFridayCloseHour    = 21;         // Friday Close Hour
input bool   InpEnableNewsFilter   = true;       // News Filter
input int    InpNewsBlockMin       = 1;          // News Block Minutes
input bool   InpEnableCorrelationGuard = false;  // Correlation Guard
input bool   InpEnableKillSwitch   = true;       // Kill Switch (22-01 UTC)

// Global Variables
CTrade trade;
int magicNumber = 202699;
datetime lastTradeTime = 0;
int consecutiveLosses = 0;
datetime lastConsecutiveLossReset = 0;
double dailyStartBalance = 0;
datetime lastDayCheck = 0;

//+------------------------------------------------------------------+
int OnInit()
{
   trade.SetExpertMagicNumber(magicNumber);
   trade.SetDeviationInPoints(5);
   trade.SetTypeFilling(ORDER_FILLING_FOK);
   dailyStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnTick()
{
   datetime now = TimeCurrent();
   MqlDateTime dt;
   TimeToStruct(now, dt);

   // 1. Friday close
   if(InpEnableFridayClose && dt.day_of_week == 5 && dt.hour >= InpFridayCloseHour)
   {
      CloseAllPositions();
      return;
   }

   // 2. Kill switch (22-01 UTC)
   if(InpEnableKillSwitch && (dt.hour >= 22 || dt.hour < 1))
      return;

   // 3. Weekend filter
   if(dt.day_of_week == 0 || dt.day_of_week == 6)
      return;

   // 4. Daily reset
   if(now - lastDayCheck >= 86400)
   {
      dailyStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
      lastDayCheck = now;
      consecutiveLosses = 0;
   }

   // 5. Drawdown checks
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double dailyDD = (dailyStartBalance - balance) / dailyStartBalance * 100;
   if(dailyDD >= InpMaxDailyLossPct)
   {
      CloseAllPositions();
      return;
   }

   double totalDD = (InpInitialBalance - balance) / InpInitialBalance * 100;
   if(totalDD >= InpMaxTotalLossPct)
   {
      CloseAllPositions();
      return;
   }

   // 6. Manage open positions
   ManageOpenPositions();

   // 7. Check if already have position
   if(PositionsTotal() > 0)
      return;

   // 8. Consecutive loss block
   if(consecutiveLosses >= InpConsecutiveLossLimit)
      return;

   // 9. Spread check
   double spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(spread > InpMaxSpreadPips)
      return;

   // 10. Volume check
   long tickVolume = iVolume(_Symbol, PERIOD_M1, 0);
   if(tickVolume < InpMinVolumeRatio)
      return;

   // 11. Session check
   if(!IsTimeWindowOpen(dt.hour))
      return;

   // 12. News filter
   if(InpEnableNewsFilter && IsNewsWindow(dt.hour, dt.min))
      return;

   // 13. Analyze M15
   int htfBias = GetHTFBias();
   if(htfBias == 0) return;

   // 14. M15 efficiency
   double efficiency = GetEfficiency();
   if(efficiency < InpMinEfficiency) return;

   // 15. M5 confirmation
   if(InpEnableM5filter && !GetM5Confirmation(htfBias)) return;

   // 16. Calculate SL
   double atr = iATR(_Symbol, PERIOD_M15, InpRegimePeriod, 1);
   double slPips = MathMax(20, MathMin(atr * InpSLatrMultiplier, MathMin(atr * 3, 60)));
   double tpPips = slPips * InpTargetRatio;

   // 17. Calculate lots
   double lots = CalculateLots(slPips);
   if(lots <= 0) return;

   // 18. Execute trade
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

   if(htfBias == 1) // BUY
   {
      double sl = ask - slPips * point * 10;
      double tp = ask + tpPips * point * 10;
      trade.Buy(lots, _Symbol, ask, sl, tp, "Alpha_v4.5_BUY");
   }
   else if(htfBias == -1) // SELL
   {
      double sl = bid + slPips * point * 10;
      double tp = bid - tpPips * point * 10;
      trade.Sell(lots, _Symbol, bid, sl, tp, "Alpha_v4.5_SELL");
   }
}

//+------------------------------------------------------------------+
void ManageOpenPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(!PositionSelectByTicket(ticket)) continue;

      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSL = PositionGetDouble(POSITION_SL);
      double currentTP = PositionGetDouble(POSITION_TP);
      double profit = PositionGetDouble(POSITION_PROFIT);
      datetime openTime = (datetime)PositionGetInteger(POSITION_TIME);

      double atr = iATR(_Symbol, PERIOD_M15, InpRegimePeriod, 1);

      // Duration check
      int minutesOpen = (int)((TimeCurrent() - openTime) / 60);
      if(minutesOpen >= InpMaxTradeDuration)
      {
         trade.PositionClose(ticket);
         continue;
      }

      // Partial profit -> move SL to breakeven
      double tpDistance = currentTP - openPrice;
      if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)
      {
         double partialPrice = openPrice + tpDistance * InpPartialProfitPct;
         if(SymbolInfoDouble(_Symbol, SYMBOL_BID) >= partialPrice && currentSL < openPrice)
         {
            trade.PositionModify(ticket, openPrice, currentTP);
         }

         // Trailing stop
         double trailingSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - atr * InpTrailingATRmult;
         if(trailingSL > currentSL && trailingSL > openPrice)
         {
            trade.PositionModify(ticket, trailingSL, currentTP);
         }
      }
      else
      {
         double partialPrice = openPrice - MathAbs(tpDistance) * InpPartialProfitPct;
         if(SymbolInfoDouble(_Symbol, SYMBOL_ASK) <= partialPrice && currentSL > openPrice)
         {
            trade.PositionModify(ticket, openPrice, currentTP);
         }

         double trailingSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + atr * InpTrailingATRmult;
         if(trailingSL < currentSL && trailingSL < openPrice)
         {
            trade.PositionModify(ticket, trailingSL, currentTP);
         }
      }
   }
}

//+------------------------------------------------------------------+
void CloseAllPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      trade.PositionClose(ticket);
   }
}

//+------------------------------------------------------------------+
int GetHTFBias()
{
   if(!InpEnableHTFFilter) return(0);

   double ema50 = iMA(_Symbol, PERIOD_H1, InpEMAperiodH1, 0, MODE_EMA, PRICE_CLOSE, 0);
   double price = iClose(_Symbol, PERIOD_M1, 0);

   if(price > ema50 + InpMinMAalignment * SymbolInfoDouble(_Symbol, SYMBOL_POINT) * 10)
      return(1);  // Bullish
   else if(price < ema50 - InpMinMAalignment * SymbolInfoDouble(_Symbol, SYMBOL_POINT) * 10)
      return(-1); // Bearish

   return(0);
}

//+------------------------------------------------------------------+
double GetEfficiency()
{
   double closes[];
   ArrayResize(closes, InpRegimePeriod + 1);
   for(int i = 0; i <= InpRegimePeriod; i++)
      closes[i] = iClose(_Symbol, PERIOD_M15, i);

   double netChange = MathAbs(closes[0] - closes[InpRegimePeriod]);
   double sumVol = 0;
   for(int i = 0; i < InpRegimePeriod; i++)
      sumVol += MathAbs(closes[i] - closes[i + 1]);

   if(sumVol == 0) return(0);
   return(netChange / sumVol);
}

//+------------------------------------------------------------------+
bool GetM5Confirmation(int bias)
{
   int bullishCount = 0;
   int bearishCount = 0;

   for(int i = 0; i < InpM5trendBars; i++)
   {
      double close = iClose(_Symbol, PERIOD_M5, i);
      double open = iOpen(_Symbol, PERIOD_M5, i);
      if(close > open) bullishCount++;
      else bearishCount++;
   }

   if(bias == 1 && bullishCount >= InpM5trendBars / 2) return(true);
   if(bias == -1 && bearishCount >= InpM5trendBars / 2) return(true);
   return(false);
}

//+------------------------------------------------------------------+
bool IsTimeWindowOpen(int hour)
{
   if(hour >= InpLondonStart && hour < InpLondonEnd) return(true);
   if(hour >= InpNYStart && hour < InpNYEnd) return(true);
   if(hour >= InpAsiaStart && hour < InpAsiaEnd) return(true);
   return(false);
}

//+------------------------------------------------------------------+
bool IsNewsWindow(int hour, int min)
{
   int newsHours[] = {12, 14, 18};
   for(int i = 0; i < ArraySize(newsHours); i++)
   {
      if(hour == newsHours[i] && min < InpNewsBlockMin) return(true);
      if(hour == newsHours[i] - 1 && min > 60 - InpNewsBlockMin) return(true);
   }
   return(false);
}

//+------------------------------------------------------------------+
double CalculateLots(double slPips)
{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskPct = InpRiskPerTradePct / 100.0;

   // Risk taper based on DD
   double dd = (InpInitialBalance - balance) / InpInitialBalance * 100;
   if(dd > 2.0)
      riskPct *= MathMax(0.25, 1.0 - (dd - 2.0) * InpRiskTaperDDmult * 0.1);

   double riskMoney = balance * riskPct;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);

   if(tickValue <= 0 || tickSize <= 0 || price <= 0) return(0);

   double slPoints = slPips * 10;
   double lots = riskMoney / (slPoints * tickValue / tickSize);

   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);

   lots = MathFloor(lots / step) * step;
   lots = MathMax(lots, minLot);
   lots = MathMin(lots, maxLot);

   // Margin check
   double marginRequired = lots * price * SymbolInfoInteger(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE) / 100;
   double freeMargin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   if(marginRequired > freeMargin * 0.3) return(0);

   return(lots);
}

//+------------------------------------------------------------------+
void OnTrade()
{
   if(HistorySelect(0, TimeCurrent()))
   {
      int totalDeals = HistoryDealsTotal();
      if(totalDeals > 0)
      {
         ulong lastDeal = HistoryDealGetTicket(totalDeals - 1);
         if(HistoryDealGetInteger(lastDeal, DEAL_MAGIC) == magicNumber)
         {
            double profit = HistoryDealGetDouble(lastDeal, DEAL_PROFIT);
            if(profit < 0)
            {
               consecutiveLosses++;
               lastConsecutiveLossReset = TimeCurrent();
            }
            else
            {
               consecutiveLosses = 0;
            }
         }
      }
   }
}
