//+------------------------------------------------------------------+
//| grid_EURUSD_M30_63d643.mq5
//| Generated by QuantLab — 2026-07-04T01:57:23.465262+00:00
//| Pattern: grid | TF: M30 | Symbol: EURUSD
//+------------------------------------------------------------------+
#property copyright "QuantLab"
#property version   "1"
#property strict

#include <Trade\Trade.mqh>

input double InpLotSize = 0.02;
input int    InpStopLoss = 106;
input int    InpTakeProfit = 88;
input int    InpTrailingStop = 77;
input int    InpMaxPositions = 4;

CTrade trade;
datetime lastBarTime = 0;

int OnInit() {
    trade.SetExpertMagicNumber(MAGIC_NUMBER);
    return(INIT_SUCCEEDED);
}

void OnTick() {
    datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
    if(currentBarTime == lastBarTime) return;
    lastBarTime = currentBarTime;

    ManageTrailingStop();
    ExecuteStrategy();
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            count++;
    }
    return count;
}

void ManageTrailingStop() {
    if(InpTrailingStop <= 0) return;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) != _Symbol) continue;
        if(PositionGetInteger(POSITION_MAGIC) != MAGIC_NUMBER) continue;
        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
        double currentSL = PositionGetDouble(POSITION_SL);
        ulong ticket = PositionGetInteger(POSITION_TICKET);
        if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_BID) - InpTrailingStop * _Point;
            if(newSL > currentSL + _Point)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        } else {
            double newSL = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + InpTrailingStop * _Point;
            if(newSL < currentSL - _Point || currentSL == 0)
                trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
        }
    }
}

void CloseAll() {
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MAGIC_NUMBER)
            trade.PositionClose(PositionGetInteger(POSITION_TICKET));
    }
}

#define MAGIC_NUMBER 825714

int emaFastHandle, emaSlowHandle, adxHandle, atrHandle;

int OnInit() {
    emaFastHandle = iMA(_Symbol, PERIOD_CURRENT, 13, 0, MODE_EMA, PRICE_CLOSE);
    emaSlowHandle = iMA(_Symbol, PERIOD_CURRENT, 29, 0, MODE_EMA, PRICE_CLOSE);
    adxHandle = iADX(_Symbol, PERIOD_CURRENT, 14);
    atrHandle = iATR(_Symbol, PERIOD_CURRENT, 10);
    return INIT_SUCCEEDED;
}

void ExecuteStrategy() {
    if(CountPositions() >= InpMaxPositions) return;

    double emaFast[], emaSlow[], adxVal[], atrVal[];
    ArraySetAsSeries(emaFast, true);
    ArraySetAsSeries(emaSlow, true);
    ArraySetAsSeries(adxVal, true);
    ArraySetAsSeries(atrVal, true);
    CopyBuffer(emaFastHandle, 0, 0, 3, emaFast);
    CopyBuffer(emaSlowHandle, 0, 0, 3, emaSlow);
    CopyBuffer(adxHandle, 1, 0, 3, adxVal);
    CopyBuffer(atrHandle, 0, 0, 3, atrVal);

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    if(adxVal[1] < 20) return;

    if(emaFast[2] < emaSlow[2] && emaFast[1] > emaSlow[1] && adxVal[1] > 20) {
        double sl = ask - InpStopLoss * _Point;
        double tp = ask + InpTakeProfit * _Point;
        trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "grid_EURUSD_M30_63d643_BUY");
    }
    if(emaFast[2] > emaSlow[2] && emaFast[1] < emaSlow[1] && adxVal[1] > 20) {
        double sl = bid + InpStopLoss * _Point;
        double tp = bid - InpTakeProfit * _Point;
        trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "grid_EURUSD_M30_63d643_SELL");
    }
}
